### ISSUE TITLE
Script return true but no download completed

### ISSUE THREAD

**Issue by Alt0car** [yuukari/e-hentai-downloader#1]
Since a couple of days the script return false positive 
I guess they have change security and images are not downloaded but the script return a success message

❤️ Preparing to download gallery from https://e-hentai.org/g/3104570/dae8df85a0/
◻️ Gallery found!
    Title: The Simpsons "Bad Boy" By: Zoen. Patreon
    Type:
    Rating: 4.38
    Total size: 61.10 MiB
    Total pages count: 25
◻️ Parsing pages...
◻️ Parsing done in 0.09 sec
✅  Done ██████████████████████████████ 100% [25/25]

ls the folder it was empty

**Comment by yuukari** [comment]
Hi! Thank you for reporting about this problem. They made some changes to the HTML layout, make impossible to get image links by the parser. 

I fix it, you need to update your local repository.
